[tasks.build]
command = "cross"
args = [
    "build",
    "--release",
    "--target",
    "aarch64-unknown-linux-gnu",
]

[tasks.release]
dependencies = ["build"]
command = "scp"
args = [
    "target/aarch64-unknown-linux-gnu/release/shaysbot",
    "ubuntu@vps.shaybox.com:~/shaysbot",
]
